Improvements to Plugin Build and Deployment Process + remove github dependency (#1)
* Build releases with GH workflow

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* Add OpenShift image build to release workflow

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* use copy of official rh argo-rollouts image

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* fix plugin path

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* read secrets from env

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* Fix: Specify container name when fetching pod logs for multi-container pods

- Added logic to identify and use the application container (skip istio-proxy/istio-init)
- Explicitly set Container field in PodLogOptions to avoid OpenShift API rejection
- Fixes 'the server rejected our request for an unknown reason' error in multi-container pods

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* force load plugin

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* Fix: Rename log variable to logger to avoid shadowing

- Changed local variable from 'log' to 'logger' to avoid shadowing the imported log package
- Fixes compilation error: log.Fields is not a type

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* Fix: Correct rollouts-controller binary path in startup script

- Changed from /bin/rollouts-controller to /usr/local/bin/rollouts-controller
- Fixes CrashLoopBackOff: No such file or directory error

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* make ci and release gh actions workflows consistent

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* modify gh action

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* just copy the plugin to the plugins folder, the rest should happen automatically

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* startup fix for openshift image

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* go back to copying the plugin

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* remove obsolete custom openshift build

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

* fix issue with github url

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>

---------

Signed-off-by: Kevin Dubois <kevin.dubois@gmail.com>